#
# TL Config Makefile
#
# Copyright (c) 2001 The ThinLisp Group

CC = @CC@

CFLAGS =

ifdef THREAD
CFLAGS += -DPTHREAD
endif

ifdef OPT
CFLAGS += -O2 -fomit-frame-pointer
else
CFLAGS += -ggdb3
endif

CFLAGS += @CFLAGS@ -pipe -ansi -pedantic -W -Wall -c

ARCHIVE = ar rsc
OBJECTS =  tl.o boot.o stubs.o tl-types.o \
        inline.o tl-prim.o do.o format.o input.o \
        tl-basics.o loop.o apply.o generic-math.o generic-prim.o \
        packages.o tl-util.o versions.o forward.o tl-extension.o \
        tl-time.o

all : libtl.a

clean :
	-rm *.o
	-( if [ -f libtl.a ] ; then rm libtl.a ; fi )

libtl.a : makefile.config $(OBJECTS) $(LIBS)
	-( if [ -f libtl.a ] ; then rm libtl.a ; fi )
	$(ARCHIVE) libtl.a $(OBJECTS)

%.o : ../c/%.c ../c/%.h makefile.config ../c/tl.h
	$(CC) $@ $(CFLAGS) -I ../c $<
